#!/usr/bin/env python3
"""
Generates the OBJ meshes used by the SAUVC Stonefish scenario:
  - drum.obj      : SAUVC target drum, open-top hollow cylinder (60 cm dia, 30 cm deep)
  - cup.obj       : tiny cup mounted on top of the task-4 flares to hold the golf ball
  - propeller.obj : simple disc used as propeller geometry for the template vehicle

Conventions:
  - NED frame (Z axis pointing DOWN), as required by Stonefish.
  - Mesh origin at the BOTTOM CENTER of the object; the object extends in -Z (upwards).
  - Meshes are closed (watertight), triangulated, ASCII OBJ.
"""
import math
import os

OUT = os.path.join(os.path.dirname(__file__), '..', 'data')


def open_cup(outer_r, inner_r, height, bottom_t, segments=32):
    """Closed thin-walled cup, open on top (-Z side). Origin at bottom center, extends in -Z."""
    verts = []
    faces = []

    def ring(radius, z):
        start = len(verts) + 1  # OBJ is 1-indexed
        for i in range(segments):
            a = 2.0 * math.pi * i / segments
            verts.append((radius * math.cos(a), radius * math.sin(a), z))
        return start

    # z=0 bottom (outer face), z=-height rim, inner bottom at z=-bottom_t
    ob = ring(outer_r, 0.0)            # outer, bottom
    ot = ring(outer_r, -height)        # outer, top rim
    it = ring(inner_r, -height)        # inner, top rim
    ib = ring(inner_r, -bottom_t)      # inner, bottom of cavity
    cb = len(verts) + 1                # center of outer bottom
    verts.append((0.0, 0.0, 0.0))
    ci = len(verts) + 1                # center of inner cavity bottom
    verts.append((0.0, 0.0, -bottom_t))

    def quad(a, b, c, d):
        faces.append((a, b, c))
        faces.append((a, c, d))

    for i in range(segments):
        j = (i + 1) % segments
        # outer wall (normal outwards)
        quad(ob + i, ob + j, ot + j, ot + i)
        # rim (normal up, i.e. -Z)
        quad(ot + i, ot + j, it + j, it + i)
        # inner wall (normal inwards)
        quad(it + i, it + j, ib + j, ib + i)
        # inner cavity bottom fan (normal up, -Z)
        faces.append((ib + i, ib + j, ci))
        # outer bottom fan (normal down, +Z)
        faces.append((ob + j, ob + i, cb))
    return verts, faces


def disc(radius, thickness, segments=24):
    """Thin closed disc used as the propeller stand-in.
    AXIS ALONG +X: Stonefish thrusters generate thrust along, and spin the
    propeller mesh about, the actuator's LOCAL X axis - so the disc face must
    be perpendicular to X (in the YZ plane), matching the shroud opening."""
    verts = []
    faces = []
    half = thickness / 2.0

    def ring(z):
        start = len(verts) + 1
        for i in range(segments):
            a = 2.0 * math.pi * i / segments
            # (x=axis, y, z) = disc in the YZ plane
            verts.append((z, radius * math.sin(a), radius * math.cos(a)))
        return start

    top = ring(-half)
    bot = ring(half)
    ct = len(verts) + 1
    verts.append((0.0, 0.0, -half))
    cb = len(verts) + 1
    verts.append((0.0, 0.0, half))
    for i in range(segments):
        j = (i + 1) % segments
        faces.append((top + i, top + j, ct))          # top cap (-Z)
        faces.append((bot + j, bot + i, cb))          # bottom cap (+Z)
        faces.append((top + i, bot + i, bot + j))     # side
        faces.append((top + i, bot + j, top + j))
    return verts, faces


def write_obj(path, verts, faces):
    """Writes OBJ with per-face normals (required for correct shading/coloring).

    NOTE: the generators above produce faces wound for a Z-UP convention; since
    Stonefish/NED is Z-DOWN we flip every triangle here so that front faces
    (and normals) point OUTWARD/UPWARD. Without this, drum bottoms and cup
    interiors are backface-culled and appear see-through/black.
    """
    faces = [(a, c, b) for (a, b, c) in faces]

    def face_normal(tri):
        a, b, c = (verts[i - 1] for i in tri)
        u = (b[0] - a[0], b[1] - a[1], b[2] - a[2])
        w = (c[0] - a[0], c[1] - a[1], c[2] - a[2])
        n = (u[1] * w[2] - u[2] * w[1],
             u[2] * w[0] - u[0] * w[2],
             u[0] * w[1] - u[1] * w[0])
        l = math.sqrt(n[0] ** 2 + n[1] ** 2 + n[2] ** 2) or 1.0
        return (n[0] / l, n[1] / l, n[2] / l)

    with open(path, 'w') as f:
        f.write('# generated by generate_meshes.py (NED, Z down)\n')
        for v in verts:
            f.write('v {:.6f} {:.6f} {:.6f}\n'.format(*v))
        for tri in faces:
            f.write('vn {:.6f} {:.6f} {:.6f}\n'.format(*face_normal(tri)))
        for k, tri in enumerate(faces, start=1):
            f.write('f {0}//{3} {1}//{3} {2}//{3}\n'.format(tri[0], tri[1], tri[2], k))
    print('wrote', path, len(verts), 'verts,', len(faces), 'tris')


def pool_tiles_png(path, size=512, tiles=20, seed=7):
    """Random blue mosaic tile texture with grout lines (like typical pool mosaics)."""
    import random
    from PIL import Image, ImageDraw
    rng = random.Random(seed)
    palette = [
        (108, 168, 218), (66, 116, 178), (46, 84, 140), (120, 190, 210),
        (86, 150, 196), (52, 132, 158), (140, 196, 232), (70, 160, 170),
    ]
    grout = (225, 232, 238)
    img = Image.new('RGB', (size, size), grout)
    d = ImageDraw.Draw(img)
    step = size / tiles
    gap = max(1, int(step * 0.06))
    for i in range(tiles):
        for j in range(tiles):
            x0 = int(i * step) + gap
            y0 = int(j * step) + gap
            x1 = int((i + 1) * step) - gap
            y1 = int((j + 1) * step) - gap
            d.rectangle([x0, y0, x1, y1], fill=rng.choice(palette))
    img.save(path)
    print('wrote', path)


if __name__ == '__main__':
    os.makedirs(OUT, exist_ok=True)
    # SAUVC drum: 60 cm diameter, 30 cm deep, ~1.5 cm wall
    write_obj(os.path.join(OUT, 'drum.obj'), *open_cup(0.30, 0.285, 0.30, 0.015, 40))
    # Golf-ball cup on flare top: outer r 3 cm, inner r 2.4 cm, 2.5 cm tall
    write_obj(os.path.join(OUT, 'cup.obj'), *open_cup(0.030, 0.024, 0.025, 0.005, 20))
    # Propeller stand-in (Stonefish spins this to make thrust; kept small so it
    # hides inside the CAD thruster shrouds)
    write_obj(os.path.join(OUT, 'propeller.obj'), *disc(0.034, 0.008, 20))
    # Pool floor mosaic texture
    pool_tiles_png(os.path.join(OUT, 'pool_tiles.png'))
